package com.schappet.weight.controller;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.web.WebAppConfiguration;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.WebApplicationContext;

/**
 * Generated by Protogen
 * @since Tue Apr 07 08:12:26 CDT 2015
 */
@WebAppConfiguration
@ContextConfiguration({
	"classpath:spring/dispatcher-servlet.xml"
})
@Transactional
public class AbstractControllerMVCTests {
	
	@Autowired
	protected WebApplicationContext wac;

} 