package com.schappet.weight.controller;




import java.util.List;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Arrays;

import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.datatable.DataTableSearch;
import com.schappet.weight.dao.*;
import com.schappet.weight.domain.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;

/**
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since Tue Feb 16 20:51:24 CST 2016
 */
public class ActivityControllerMvcTest extends AbstractControllerMVCTests {
	
    private Activity firstActivity;
    
    @Before
    public void before() {
              // add 20 records to test database
        for(int x=1; x<21; x++){
        	Activity activity = new Activity();
        	weightDaoService.getActivityService().save(activity);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstActivity = activity;
	        }
        }   
        this.weightDaoService.getActivityService().getSession().flush();
        this.weightDaoService.getActivityService().getSession().clear();
          }

    @Test
    public void addShouldDisplayNewActivityForm() throws Exception {
       mockMvc.perform(get("/activity/add"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("activity")) 
       .andExpect(view().name("/weight/activity/edit"));
    }
    
    @Test
    public void listShouldSimplyLoadPage() throws Exception {
       mockMvc.perform(get("/activity/list"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/activity/list"));
    }
    
    @Test
    public void indexShouldDisplayListPage() throws Exception {
       mockMvc.perform(get("/activity/"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/activity/list"));
    }
    
    @Test
    public void listAltShouldLoadListOfActivitys() throws Exception {
       mockMvc.perform(get("/activity/list_alt"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("activityList")) 
       .andExpect(view().name("/weight/activity/list_alt"));
    }
    
    
          	  
    @Test
    public void saveNewShouldPersistAndRedirectToListView() throws Exception {
       long count = weightDaoService.getActivityService().count();
       
       mockMvc.perform(post("/activity/save").with(csrf())).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/activity/list"));   
       
       assertEquals("count should increase by 1", count +1 , weightDaoService.getActivityService().count());
	}
     
    @Test
    public void saveExistingShouldPersistAndRedirectToListView() throws Exception {
       long count = weightDaoService.getActivityService().count();
         
       mockMvc.perform(post("/activity/save").param("activityId", firstActivity.getActivityId().toString()).with(csrf())).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/activity/list"));   
         
       assertEquals("count NOT should increase", count , weightDaoService.getActivityService().count());
  	}      
  
    @Test
    public void editShouldLoadObjectAndDisplayForm() throws Exception {
    	mockMvc.perform(get("/activity/edit").param("activityId", firstActivity.getActivityId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("activity")) 
         .andExpect(view().name("/weight/activity/edit"));
    }
    
    @Test
    public void showShouldLoadAndDisplayObject() throws Exception {
    	mockMvc.perform(get("/activity/show").param("activityId", firstActivity.getActivityId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("activity")) 
         .andExpect(view().name("/weight/activity/show"));
    }
    
    @Test
    public void deleteGetShouldLoadAndDisplayYesNoButtons() throws Exception {
    	mockMvc.perform(get("/activity/delete").param("activityId", firstActivity.getActivityId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("activity")) 
         .andExpect(view().name("/weight/activity/delete"));
    }
    
    @Test
    public void deletePostSubmitYesShouldDeleteAndRedirectToListView() throws Exception {
        long count = weightDaoService.getActivityService().count();

       mockMvc.perform(post("/activity/delete").param("activityId", firstActivity.getActivityId().toString())
       .param("submit", "Yes").with(csrf())).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/activity/list"));  
       
       assertEquals("count should decrease by 1", count - 1 , weightDaoService.getActivityService().count());
    }
    
    @Test
    public void deletePostSubmitNoShouldNotDeleteAndRedirectToListView() throws Exception {
        long count = weightDaoService.getActivityService().count();

       mockMvc.perform(post("/activity/delete").param("activityId", firstActivity.getActivityId().toString())
       .param("submit", "No").with(csrf())).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/activity/list"));  
       
       assertEquals("count should NOT decrease by 1", count , weightDaoService.getActivityService().count());
    }
      
    @Test
    public void defaultDatatableShouldReturnJSONDataWith10Rows() throws Exception {
    	DataTableRequest dtr = getDataTableRequest( Arrays.asList("urls","activityDate","activityId","person","value" ));
    	ObjectMapper mapper = new ObjectMapper();
    	
    	mockMvc.perform(post("/activity/datatable").content(mapper.writeValueAsString(dtr))
			.param("display", "list")
			.accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
			.with(csrf()))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
    	.andExpect(jsonPath("$.recordsTotal", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.recordsFiltered", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	// max # of returned data rows should be 10 per "length" value
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", containsString("show?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("edit?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("delete?")))
        ;
    }
    	  
    @Test
    public void defaultDatatableShouldReturnJSONDataWith10RowsAndDisplayAltnerateGlyphiconURLsAsEmptyByDefault() throws Exception {
    	DataTableRequest dtr = getDataTableRequest( Arrays.asList("urls","activityDate","activityId","person","value" ));
    	ObjectMapper mapper = new ObjectMapper();
    	
    	mockMvc.perform(post("/activity/datatable").content(mapper.writeValueAsString(dtr))
			.param("display", "alternateURLs")
			.accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
			.with(csrf()))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
    	.andExpect(jsonPath("$.recordsTotal", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.recordsFiltered", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	// max # of returned data rows should be 10 per "length" value
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", is("")))
        ;
    }
    
    @Test
    public void defaultDatatableShouldReturnErrorTextForBogusColumnName() throws Exception {
    	DataTableRequest dtr = new DataTableRequest();
    	dtr.setStart(1);
    	dtr.setDraw("1");
    	dtr.setLength(10);
    	dtr.setIndividualSearch(true);
    	
    	List<DataTableColumn> columns = dtr.getColumns();
    	DataTableColumn column = new DataTableColumn("0", "asdfasdf", null, true, true, true);
    	DataTableSearch columnSearch = new DataTableSearch("", false);
    	column.setSearch(columnSearch);
    	columns.add(column);
    	dtr.setColumns(columns);
    	
    	ObjectMapper mapper = new ObjectMapper();
    	
    	mockMvc.perform(post("/activity/datatable").content(mapper.writeValueAsString(dtr))
			.param("display", "list")
			.accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
			.with(csrf()))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.recordsFiltered", is((int) weightDaoService.getActivityService().count())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0].0", is("[error: column asdfasdf not supported]")))
    	;
    }    
    	  
    @Test
    public void defaultDatatableShouldReturnExceptionBecauseCantSearchColumnThatDoesntExist() throws Exception {			
		DataTableRequest dtr = new DataTableRequest();
    	dtr.setStart(1);
    	dtr.setDraw("1");
    	dtr.setLength(10);
    	dtr.setIndividualSearch(true);
    	
    	List<DataTableColumn> columns = dtr.getColumns();
    	DataTableColumn column = new DataTableColumn("0", "asdfasdf", null, true, true, true);
    	DataTableSearch columnSearch = new DataTableSearch("epic fail", false);
    	column.setSearch(columnSearch);
    	columns.add(column);
    	dtr.setColumns(columns);
    	
    	ObjectMapper mapper = new ObjectMapper();
    	
    	mockMvc.perform(post("/activity/datatable").content(mapper.writeValueAsString(dtr))
			.param("display", "list")
			.accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
			.with(csrf()))	
    	.andExpect(status().isOk())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
    	.andExpect(jsonPath("$.recordsTotal", is(0)))
    	.andExpect(jsonPath("$.recordsFiltered", is(0)))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", hasSize(is(0))))
    	.andExpect(jsonPath("$.error", IsNull.notNullValue()))
    	;
    }      
          
    
}