package com.schappet.weight.controller;


import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.schappet.weight.dao.*;
import com.schappet.weight.domain.*;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Generated by Protogen
 * @since Tue Apr 07 08:12:26 CDT 2015
 */
@RunWith(SpringJUnit4ClassRunner.class)
public class EmailAddressControllerMvcTest extends AbstractControllerMVCTests {
	
    private MockMvc mockMvc;
    
    @Autowired
	private WeightDaoService weightDaoService;
    
    private EmailAddress firstEmailAddress;
    
    @Before
    public void setup() {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).build();

              // add 20 records to test database
        for(int x=1; x<21; x++){
        	EmailAddress emailAddress = new EmailAddress();
        	weightDaoService.getEmailAddressService().save(emailAddress);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstEmailAddress = emailAddress;
	        }
        }   
          }

    @Test
    public void addShouldDisplayNewEmailAddressForm() throws Exception {
       mockMvc.perform(get("/emailaddress/add"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("emailAddress")) 
       .andExpect(view().name("/weight/emailaddress/edit"));
    }
    
    @Test
    public void listShouldSimplyLoadPage() throws Exception {
       mockMvc.perform(get("/emailaddress/list"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/emailaddress/list"));
    }
    
    @Test
    public void indexShouldDisplayListPage() throws Exception {
       mockMvc.perform(get("/emailaddress/"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/emailaddress/list"));
    }
    
    @Test
    public void listAltShouldLoadListOfEmailAddresss() throws Exception {
       mockMvc.perform(get("/emailaddress/list_alt"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("emailAddressList")) 
       .andExpect(view().name("/weight/emailaddress/list_alt"));
    }
    
    
       /*   	  
    @Test
    public void saveShouldPersistAndRedirectToListView() throws Exception {
       int count = weightDaoService.getEmailAddressService().list().size();
       
       mockMvc.perform(post("/emailaddress/save")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/emailaddress/list"));   
       
       assertEquals("EmailAddress count should increase by 1", count +1 , weightDaoService.getEmailAddressService().list().size());
	}
  */
    @Test
    public void editShouldLoadObjectAndDisplayForm() throws Exception {
    	mockMvc.perform(get("/emailaddress/edit").param("emailId", firstEmailAddress.getEmailId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("emailAddress")) 
         .andExpect(view().name("/weight/emailaddress/edit"));
    }
    
    @Test
    public void showShouldLoadAndDisplayObject() throws Exception {
    	mockMvc.perform(get("/emailaddress/show").param("emailId", firstEmailAddress.getEmailId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("emailAddress")) 
         .andExpect(view().name("/weight/emailaddress/show"));
    }
    
    @Test
    public void deleteGetShouldLoadAndDisplayYesNoButtons() throws Exception {
    	mockMvc.perform(get("/emailaddress/delete").param("emailId", firstEmailAddress.getEmailId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("emailAddress")) 
         .andExpect(view().name("/weight/emailaddress/delete"));
    }
    
    @Test
    public void deletePostSubmitYesShouldDeleteAndRedirectToListView() throws Exception {
        int count = weightDaoService.getEmailAddressService().list().size();

       mockMvc.perform(post("/emailaddress/delete").param("emailId", firstEmailAddress.getEmailId().toString())
       .param("submit", "Yes")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/emailaddress/list"));  
       
       assertEquals("count should decrease by 1", count - 1 , weightDaoService.getEmailAddressService().list().size());
    }
    
    @Test
    public void deletePostSubmitNoShouldNotDeleteAndRedirectToListView() throws Exception {
        int count = weightDaoService.getEmailAddressService().list().size();

       mockMvc.perform(post("/emailaddress/delete").param("emailId", firstEmailAddress.getEmailId().toString())
       .param("submit", "No")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/emailaddress/list"));  
       
       assertEquals("count should NOT decrease by 1", count , weightDaoService.getEmailAddressService().list().size());
    }
      
    @Test
    public void defaultDatatableShouldReturnJSONDataWith10Rows() throws Exception {
    	mockMvc.perform(get("/emailaddress/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "0")
			.param("columnCount", "2")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("columns[0][data]","0").param("columns[0][name]","urls").param("columns[0][searchable]","false").param("columns[0][orderable]","false").param("columns[0][search][regex]","false").param("columns[0][search][value]","")
						.param("columns[1][data]","1").param("columns[1][name]","address").param("columns[1][searchable]","true").param("columns[1][orderable]","true").param("columns[1][search][regex]","false").param("columns[1][search][value]","")
						.param("columns[2][data]","2").param("columns[2][name]","password").param("columns[2][searchable]","true").param("columns[2][orderable]","true").param("columns[2][search][regex]","false").param("columns[2][search][value]","")
						.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(weightDaoService.getEmailAddressService().list().size())))
    	.andExpect(jsonPath("$.recordsFiltered", is(weightDaoService.getEmailAddressService().list().size())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	// max # of returned data rows should be 10 per "length" value
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", containsString("show?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("edit?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("delete?")))
        ;
    }
    	  
    @Test
    public void defaultDatatableShouldReturnErrorTextForBogusColumnName() throws Exception {
    	mockMvc.perform(get("/emailaddress/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "1")
			.param("columnCount", "1")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("columns[0][data]","0").param("columns[0][name]","asdfasdf").param("columns[0][searchable]","true").param("columns[0][orderable]","true").param("columns[0][search][regex]","false").param("columns[0][search][value]","")
			.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(weightDaoService.getEmailAddressService().list().size())))
    	.andExpect(jsonPath("$.recordsFiltered", is(weightDaoService.getEmailAddressService().list().size())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", is("[error: column asdfasdf not supported]")))
    	;
    }    
    	  
    @Test
    public void defaultDatatableShouldReturnException() throws Exception {
    	mockMvc.perform(get("/emailaddress/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "1")
			.param("columnCount", "1")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("order[0][column]","1").param(".order[0][dir]", "asc")
			.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(0)))
    	.andExpect(jsonPath("$.recordsFiltered", is(0)))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", IsNull.nullValue()))
    //	.andExpect(jsonPath("$.error", is("")))
    	;
    }      
          
    
}