package com.schappet.weight.controller;


import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.schappet.weight.dao.*;
import com.schappet.weight.domain.*;
import static org.hamcrest.Matchers.containsString;
import static org.hamcrest.Matchers.hasSize;
import static org.hamcrest.Matchers.is;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.print;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

/**
 * Generated by Protogen
 * @since Tue Apr 07 08:12:26 CDT 2015
 */
@RunWith(SpringJUnit4ClassRunner.class)
public class PersonControllerMvcTest extends AbstractControllerMVCTests {
	
    private MockMvc mockMvc;
    
    @Autowired
	private WeightDaoService weightDaoService;
    
    private Person firstPerson;
    
    @Before
    public void setup() {
        this.mockMvc = MockMvcBuilders.webAppContextSetup(this.wac).build();

              // add 20 records to test database
        for(int x=1; x<21; x++){
        	Person person = new Person();
        	weightDaoService.getPersonService().save(person);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstPerson = person;
	        }
        }   
          }

    @Test
    public void addShouldDisplayNewPersonForm() throws Exception {
       mockMvc.perform(get("/person/add"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("person")) 
       .andExpect(view().name("/weight/person/edit"));
    }
    
    @Test
    public void listShouldSimplyLoadPage() throws Exception {
       mockMvc.perform(get("/person/list"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/person/list"));
    }
    
    @Test
    public void indexShouldDisplayListPage() throws Exception {
       mockMvc.perform(get("/person/"))
       .andExpect(status().isOk())
       .andExpect(view().name("/weight/person/list"));
    }
    
    @Test
    public void listAltShouldLoadListOfPersons() throws Exception {
       mockMvc.perform(get("/person/list_alt"))
       .andExpect(status().isOk())
       .andExpect(model().attributeExists("personList")) 
       .andExpect(view().name("/weight/person/list_alt"));
    }
    
    
       /*   	  
    @Test
    public void saveShouldPersistAndRedirectToListView() throws Exception {
       int count = weightDaoService.getPersonService().list().size();
       
       mockMvc.perform(post("/person/save")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/person/list"));   
       
       assertEquals("Person count should increase by 1", count +1 , weightDaoService.getPersonService().list().size());
	}
  */
    @Test
    public void editShouldLoadObjectAndDisplayForm() throws Exception {
    	mockMvc.perform(get("/person/edit").param("personId", firstPerson.getPersonId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("person")) 
         .andExpect(view().name("/weight/person/edit"));
    }
    
    @Test
    public void showShouldLoadAndDisplayObject() throws Exception {
    	mockMvc.perform(get("/person/show").param("personId", firstPerson.getPersonId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("person")) 
         .andExpect(view().name("/weight/person/show"));
    }
    
    @Test
    public void deleteGetShouldLoadAndDisplayYesNoButtons() throws Exception {
    	mockMvc.perform(get("/person/delete").param("personId", firstPerson.getPersonId().toString()))
         .andExpect(status().isOk())
         .andExpect(model().attributeExists("person")) 
         .andExpect(view().name("/weight/person/delete"));
    }
    
    @Test
    public void deletePostSubmitYesShouldDeleteAndRedirectToListView() throws Exception {
        int count = weightDaoService.getPersonService().list().size();

       mockMvc.perform(post("/person/delete").param("personId", firstPerson.getPersonId().toString())
       .param("submit", "Yes")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/person/list"));  
       
       assertEquals("count should decrease by 1", count - 1 , weightDaoService.getPersonService().list().size());
    }
    
    @Test
    public void deletePostSubmitNoShouldNotDeleteAndRedirectToListView() throws Exception {
        int count = weightDaoService.getPersonService().list().size();

       mockMvc.perform(post("/person/delete").param("personId", firstPerson.getPersonId().toString())
       .param("submit", "No")).andExpect(status().is3xxRedirection()).andExpect(view().name("redirect:/person/list"));  
       
       assertEquals("count should NOT decrease by 1", count , weightDaoService.getPersonService().list().size());
    }
      
    @Test
    public void defaultDatatableShouldReturnJSONDataWith10Rows() throws Exception {
    	mockMvc.perform(get("/person/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "0")
			.param("columnCount", "5")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("columns[0][data]","0").param("columns[0][name]","urls").param("columns[0][searchable]","false").param("columns[0][orderable]","false").param("columns[0][search][regex]","false").param("columns[0][search][value]","")
						.param("columns[1][data]","1").param("columns[1][name]","emailId").param("columns[1][searchable]","true").param("columns[1][orderable]","true").param("columns[1][search][regex]","false").param("columns[1][search][value]","")
						.param("columns[2][data]","2").param("columns[2][name]","firstName").param("columns[2][searchable]","true").param("columns[2][orderable]","true").param("columns[2][search][regex]","false").param("columns[2][search][value]","")
						.param("columns[3][data]","3").param("columns[3][name]","lastName").param("columns[3][searchable]","true").param("columns[3][orderable]","true").param("columns[3][search][regex]","false").param("columns[3][search][value]","")
						.param("columns[4][data]","4").param("columns[4][name]","middleName").param("columns[4][searchable]","true").param("columns[4][orderable]","true").param("columns[4][search][regex]","false").param("columns[4][search][value]","")
						.param("columns[5][data]","5").param("columns[5][name]","password").param("columns[5][searchable]","true").param("columns[5][orderable]","true").param("columns[5][search][regex]","false").param("columns[5][search][value]","")
						.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(weightDaoService.getPersonService().list().size())))
    	.andExpect(jsonPath("$.recordsFiltered", is(weightDaoService.getPersonService().list().size())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	// max # of returned data rows should be 10 per "length" value
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", containsString("show?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("edit?")))
		.andExpect(jsonPath("$.data[0][0]", containsString("delete?")))
        ;
    }
    	  
    @Test
    public void defaultDatatableShouldReturnErrorTextForBogusColumnName() throws Exception {
    	mockMvc.perform(get("/person/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "1")
			.param("columnCount", "1")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("columns[0][data]","0").param("columns[0][name]","asdfasdf").param("columns[0][searchable]","true").param("columns[0][orderable]","true").param("columns[0][search][regex]","false").param("columns[0][search][value]","")
			.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(weightDaoService.getPersonService().list().size())))
    	.andExpect(jsonPath("$.recordsFiltered", is(weightDaoService.getPersonService().list().size())))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", hasSize(is(10))))
    	.andExpect(jsonPath("$.data[0][0]", is("[error: column asdfasdf not supported]")))
    	;
    }    
    	  
    @Test
    public void defaultDatatableShouldReturnException() throws Exception {
    	mockMvc.perform(get("/person/datatable")
			.param("display", "list")
			.param("search[value]", "")
			.param("search[regex]", "false")
			.param("length", "10")
			.param("start", "1")
			.param("columnCount", "1")
			.param("draw", "1")
			.param("individualSearch", "true")
			.param("order[0][column]","1").param(".order[0][dir]", "asc")
			.accept(MediaType.APPLICATION_JSON))
    	.andExpect(status().isOk())
    	.andExpect(content().contentType("application/json"))
    	.andExpect(jsonPath("$.recordsTotal", is(0)))
    	.andExpect(jsonPath("$.recordsFiltered", is(0)))
    	.andExpect(jsonPath("$.draw", is("1")))
    	.andExpect(jsonPath("$.data", IsNull.nullValue()))
    //	.andExpect(jsonPath("$.error", is("")))
    	;
    }      
          
    
}