package com.schappet.defaultSchema.resource;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import com.schappet.defaultSchema.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:30:14 CST
 */
@RestController( value = "com_schappet_defaultSchema_resource_vitals_resource" )
@RequestMapping( "/rest/vitals" )
public class VitalsResource extends AbstractDefaultSchemaApiResource {

    private static final Log log = LogFactory.getLog( VitalsResource.class );
    
    @RequestMapping( value = { "{vitalsId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public Vitals get( @PathVariable( "vitalsId" ) Integer vitalsId ) {
    	 Vitals vitals = defaultSchemaDaoService.getVitalsService().findById( vitalsId );
		 if (vitals == null){
			 throw new EntityNotFoundException();
		 } 
	     return vitals;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Vitals create( @RequestBody @Valid Vitals vitals ) {
		 defaultSchemaDaoService.getVitalsService().save( vitals );
		 return vitals;
    }
    
    @RequestMapping( value = { "{vitalsId}" }, method = { RequestMethod.POST, RequestMethod.PUT }, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Vitals update( @PathVariable( "vitalsId" ) Integer vitalsId, @RequestBody @Valid Vitals vitals ) {
    	Vitals vitalsRecord = defaultSchemaDaoService.getVitalsService().findById( vitalsId );
    	if ( vitalsRecord == null || !vitalsRecord.getVitalsId().equals(vitals.getVitalsId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 defaultSchemaDaoService.getVitalsService().getSession().flush();
         defaultSchemaDaoService.getVitalsService().getSession().clear();
		 defaultSchemaDaoService.getVitalsService().update( vitals );
		 return vitals;
    }
    
    @RequestMapping( value = { "{vitalsId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete( @PathVariable( "vitalsId" ) Integer vitalsId ) {
    	Vitals vitals = defaultSchemaDaoService.getVitalsService().findById( vitalsId );
		 if ( vitals == null ){
			 throw new EntityNotFoundException();
		 } 
		 defaultSchemaDaoService.getVitalsService().delete(vitals);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<Vitals> list() {
    	 return defaultSchemaDaoService.getVitalsService().list();
    }

}