package com.schappet.weight.domain;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.format.annotation.DateTimeFormat;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @since 04/11/2015 07:34:51 AM CDT
 */
@Entity( name = "com_schappet_weight_domain_activity" )
@Table( name = "activity", schema = "weight" )
public class Activity { 

	private static final Log log = LogFactory.getLog(Activity.class);

    private Integer activityId;
    private Integer personId;
    private String value;

    @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date activityDate;

    public Activity() {
    	
    }
    
    

	public Activity(String csv, int personId)  {
		
    	String[] parts = csv.split(",");
    	try  {
	    	String date[] = parts[0].split("/");
	    	int month = Integer.parseInt(date[0]);
	    	int day = Integer.parseInt(date[1]);
	    	int year = Integer.parseInt(date[2]);
	    	
	    	Calendar calendar = new GregorianCalendar(year,month -1 ,day);
	    	
	    	this.activityDate = calendar.getTime();
    	} catch (NumberFormatException nfe) {
    		throw new NumberFormatException();
    	}
    	this.personId=personId;
    	try {
    		this.value = parts[4];	
    	} catch( ArrayIndexOutOfBoundsException aioobe) {
    		throw new ArrayIndexOutOfBoundsException();
    	}
        
    	
    }

    
    @Override
	public String toString() {
        DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");

		return "Activity [activityId=" + activityId + ", personId=" + personId
				+ ", value=" + value + ", activityDate=" + formatter.format(activityDate) + "]";
	}
    
    
    /*****activityId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="weight.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "activity_id", unique = true, nullable = false)
    public Integer getActivityId(){
        return activityId;
    }

    public void setActivityId(Integer activityId){
        this.activityId = activityId;
    }

    /*****personId*****/
    @Column(name = "person_id")
    public Integer getPersonId(){
        return personId;
    }

    public void setPersonId(Integer personId){
        this.personId = personId;
    }

    /*****value*****/
    @Column(name = "value")
    public String getValue(){
        return value;
    }

    public void setValue(String value){
        this.value = value;
    }

    /*****activityDate*****/
    @Column(name = "activity_date")
    public Date getActivityDate(){
        return activityDate;
    }

    public void setActivityDate(Date activityDate){
        this.activityDate = activityDate;
    }

    public void setActivityDate(String activityDate){
        try{
            DateFormat formatter = new SimpleDateFormat("yyyy-MM-dd");
            formatter.setLenient(true);
            this.activityDate = formatter.parse(activityDate);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for ActivityDate", e);
        }
    }


}
