package com.schappet.weight.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Column;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import com.schappet.*;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @since 04/11/2015 07:34:51 AM CDT
 */
@Entity( name = "com_schappet_weight_domain_activity" )
@Table( name = "activity", schema = "weight" )
public class Activity { 

	private static final Log log = LogFactory.getLog(Activity.class);

        private Integer activityId;
        private Integer personId;
        private String value;
        @DateTimeFormat(pattern = "yyyy-MM-dd")
    private Date activityDate;


    /*****activityId*****/
    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="weight.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "activity_id", unique = true, nullable = false)
    public Integer getActivityId(){
        return activityId;
    }

    public void setActivityId(Integer activityId){
        this.activityId = activityId;
    }

    /*****personId*****/
    @Column(name = "person_id")
    public Integer getPersonId(){
        return personId;
    }

    public void setPersonId(Integer personId){
        this.personId = personId;
    }

    /*****value*****/
    @Column(name = "value")
    public String getValue(){
        return value;
    }

    public void setValue(String value){
        this.value = value;
    }

    /*****activityDate*****/
    @Column(name = "activity_date")
    public Date getActivityDate(){
        return activityDate;
    }

    public void setActivityDate(Date activityDate){
        this.activityDate = activityDate;
    }

    public void setActivityDate(String activityDate){
        try{
            DateFormat formatter = new SimpleDateFormat("MM/dd/yyyy");
            formatter.setLenient(true);
            this.activityDate = formatter.parse(activityDate);
        } catch (ParseException e) { 
            log.error(" ParseException setting date for ActivityDate", e);
        }
    }


}
