package com.schappet.weight.domain;

import java.util.Set;
import java.util.*;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.Date;
import javax.persistence.*;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Table;
import javax.persistence.Table;

import org.springframework.format.annotation.DateTimeFormat;
import org.hibernate.annotations.*;
import javax.persistence.CascadeType;
import javax.validation.constraints.NotNull;
import com.fasterxml.jackson.annotation.*;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.schappet.*;
import com.schappet.util.JsonDateDeserializer;
import com.schappet.util.JsonDateSerializer;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/03/2016 06:46:12 AM CDT
 */
@Entity( name = "com_schappet_weight_domain_heartRate" )
@Table( name = "heart_rate", schema = "weight" )
@JsonIgnoreProperties( { "hibernateLazyInitializer", "handler" } )
public class HeartRate { 

	private static final Log log = LogFactory.getLog( HeartRate.class );

    private Integer heartRateId;
    private String value;
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    @JsonSerialize(using=JsonDateSerializer.class)
    @JsonDeserialize(using=JsonDateDeserializer.class)
    private Date measureDate;
    private Person person;


    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="weight.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "heart_rate_id", unique = true, nullable = false)
    public Integer getHeartRateId(){
        return heartRateId;
    }

    public void setHeartRateId(Integer heartRateId){
        this.heartRateId = heartRateId;
    }

    @Column(name = "value")
    public String getValue(){
        return value;
    }

    public void setValue(String value){
        this.value = value;
    }

    @Column(name = "measure_date")
    public Date getMeasureDate(){
        return measureDate;
    }

    @JsonSetter
    public void setMeasureDate(Date measureDate){
        this.measureDate = measureDate;
    }

    @JsonIgnore
    public void setMeasureDate( String measureDate ){
        try{
            DateFormat formatter = new SimpleDateFormat( "MM/dd/yyyy" );
            formatter.setLenient(true);
            this.measureDate = formatter.parse(measureDate);
        } catch ( ParseException e ) { 
            log.error( "ParseException setting date for MeasureDate", e );
        }
    }

    @ManyToOne(fetch = FetchType.LAZY,  targetEntity=Person.class )
    @JoinColumn(name = "person_id",nullable = true)
    public Person getPerson(){
        return person;
    }

    public void setPerson(Person person){
        this.person = person;
    }


    @Transient
    public String getPersonName() {
    	if (person != null ) {
    		return person.getFullName();
    	} else {
    		return "";
    	}
    }

}
