package com.schappet.weight.domain;

import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonSetter;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.schappet.util.JsonDateSerializer;

/** 
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:33:31 PM CST
 */
@Entity( name = "com_schappet_weight_domain_metric" )
@Table( name = "metric", schema = "weight" )
@JsonIgnoreProperties( { "hibernateLazyInitializer", "handler" } )
public class Metric { 

	private static final Log log = LogFactory.getLog( Metric.class );

    private Integer metricId;
    private String name;
    private String textValue;
    private Double numericValue;
    @DateTimeFormat( pattern = "yyyy-MM-dd" )
    @JsonSerialize(using=JsonDateSerializer.class)
    private Date dateAdded;
    private String source;


    @javax.persistence.SequenceGenerator(  name="gen",  sequenceName="weight.seqnum",allocationSize=1)
    @Id
    @GeneratedValue( strategy=GenerationType.AUTO,generator="gen")
    @Column(name = "metric_id", unique = true, nullable = false)
    public Integer getMetricId(){
        return metricId;
    }

    public void setMetricId(Integer metricId){
        this.metricId = metricId;
    }

    @Column(name = "name")
    public String getName(){
        return name;
    }

    public void setName(String name){
        this.name = name;
    }

    @Column(name = "text_value")
    public String getTextValue(){
        return textValue;
    }

    public void setTextValue(String textValue){
        this.textValue = textValue;
    }

    @Column(name = "numeric_value")
    public Double getNumericValue(){
        return numericValue;
    }

    public void setNumericValue(Double numericValue){
        this.numericValue = numericValue;
    }

    @Column(name = "date_added")
    public Date getDateAdded(){
        return dateAdded;
    }

    @JsonSetter
    public void setDateAdded(Date dateAdded){
        this.dateAdded = dateAdded;
    }

    @JsonIgnore
    public void setDateAdded( String dateAdded ){
        try{
            DateFormat formatter = new SimpleDateFormat( "MM/dd/yyyy" );
            formatter.setLenient(true);
            this.dateAdded = formatter.parse(dateAdded);
        } catch ( ParseException e ) { 
            log.error( "ParseException setting date for DateAdded", e );
        }
    }

    @Column(name = "source")
    public String getSource(){
        return source;
    }

    public void setSource(String source){
        this.source = source;
    }


}
