package com.schappet.weight.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

/** 
 * Generated by Protogen - www.icts.uiowa.edu/protogen 
 * @since 04/11/2015 07:34:51 AM CDT
 */
@Entity( name = "com_schappet_weight_domain_summaryTable" )
@Table( name = "summary_table", schema = "weight" )
public class SummaryTable { 

	private static final Log log = LogFactory.getLog(SummaryTable.class);

	private Integer id;
    private Integer personId;
    private String monthYear;
    private Float totalActivity;
    private Float avgWeight;
    
        
    
    /*****activityId*****/
    @Id
    @Column(name = "id", unique = true, nullable = false)
    public Integer getId(){
        return id;
    }

    public void setId(Integer id){
        this.id = id;
    }

    /*****personId*****/
    @Column(name = "person_id")
    public Integer getPersonId(){
        return personId;
    }

    public void setPersonId(Integer personId){
        this.personId = personId;
    }

    @Column(name = "month_year")
	public String getMonthYear() {
		return monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}

	@Column(name = "total_activity")
	public Float getTotalActivity() {
		return totalActivity;
	}

	public void setTotalActivity(Float totalActivity) {
		this.totalActivity = totalActivity;
	}

	@Column(name = "avg_weight")
	public Float getAvgWeight() {
		return avgWeight;
	}

	public void setAvgWeight(Float avgWeight) {
		this.avgWeight = avgWeight;
	}


}
