package com.schappet.weight.domain;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Generated by Protogen - www.icts.uiowa.edu/protogen
 * 
 * @since 04/11/2015 07:34:51 AM CDT
 */
@Entity(name = "com_schappet_weight_domain_summary_vitals")
@Table(name = "summary_vitals", schema = "weight")
public class SummaryVitals {

	//private static final Log log = LogFactory.getLog(SummaryVitals.class);

	private Integer id;

	private Integer personId;

	private String monthYear;
	private Float avgSystolic;
	private Float minSystolic;
	private Float maxSystolic;

	private Float avgDiatolic;
	private Float minDiatolic;
	private Float maxDiatolic;

	private Float avgPulse;
	private Float minPulse;
	private Float maxPulse;

	/***** vitalsId *****/
	@Id
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	/***** personId *****/
	@Column(name = "person_id")
	public Integer getPersonId() {
		return personId;
	}

	public void setPersonId(Integer personId) {
		this.personId = personId;
	}



	@Column(name = "avg_systolic")
	public Float getAvgSystolic() {
		return avgSystolic;
	}

	@Column(name = "month_year")
	public String getMonthYear() {
		return monthYear;
	}

	public void setMonthYear(String monthYear) {
		this.monthYear = monthYear;
	}

	public void setAvgSystolic(Float avgSystolic) {
		this.avgSystolic = avgSystolic;
	}

	@Column(name = "min_systolic")
	public Float getMinSystolic() {
		return minSystolic;
	}

	public void setMinSystolic(Float minSystolic) {
		this.minSystolic = minSystolic;
	}

	@Column(name = "max_systolic")
	public Float getMaxSystolic() {
		return maxSystolic;
	}

	public void setMaxSystolic(Float maxSystolic) {
		this.maxSystolic = maxSystolic;
	}

	@Column(name = "avg_diatolic")
	public Float getAvgDiatolic() {
		return avgDiatolic;
	}

	public void setAvgDiatolic(Float avgDiatolic) {
		this.avgDiatolic = avgDiatolic;
	}

	@Column(name = "min_diatolic")
	public Float getMinDiatolic() {
		return minDiatolic;
	}

	public void setMinDiatolic(Float minDiatolic) {
		this.minDiatolic = minDiatolic;
	}

	@Column(name = "max_diatolic")
	public Float getMaxDiatolic() {
		return maxDiatolic;
	}

	public void setMaxDiatolic(Float maxDiatolic) {
		this.maxDiatolic = maxDiatolic;
	}

	@Column(name = "avg_pulse")
	public Float getAvgPulse() {
		return avgPulse;
	}

	public void setAvgPulse(Float avgPulse) {
		this.avgPulse = avgPulse;
	}

	@Column(name = "min_pulse")
	public Float getMinPulse() {
		return minPulse;
	}

	public void setMinPulse(Float minPulse) {
		this.minPulse = minPulse;
	}

	@Column(name = "max_pulse")
	public Float getMaxPulse() {
		return maxPulse;
	}

	public void setMaxPulse(Float maxPulse) {
		this.maxPulse = maxPulse;
	}

}
