package com.schappet.weight.resource;




import java.util.List;

import org.hamcrest.core.IsNull;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.MediaType;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.test.web.servlet.MockMvc;
import org.springframework.test.web.servlet.setup.MockMvcBuilders;

import com.fasterxml.jackson.databind.ObjectMapper;

import java.util.Arrays;

import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import edu.uiowa.icts.datatable.DataTableSearch;
import com.schappet.weight.dao.*;
import com.schappet.weight.domain.*;
import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertThat;
import static org.hamcrest.Matchers.*;
import static org.springframework.test.web.servlet.result.MockMvcResultHandlers.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
import com.schappet.weight.controller.AbstractControllerMVCTests;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*;

/**
 * Generated by Protogen
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since Tue Feb 16 20:51:24 CST 2016
 */
public class MetricResourceMvcTest extends AbstractControllerMVCTests {
	
    private Metric firstMetric;
    private ObjectMapper mapper;
    
    @Before
    public void before() { 
        // add 20 records to test database
        for(int x=1; x<21; x++){
        	Metric metric = new Metric();
        	weightDaoService.getMetricService().save(metric);
	        if (x == 1){
	        	// use this ID for update, show, and delete assertions
	        	firstMetric = metric;
	        }
        }   
        this.mapper = new ObjectMapper();
        // fix NonUniqueObjectException
        this.weightDaoService.getMetricService().getSession().flush();
        this.weightDaoService.getMetricService().getSession().clear();
    }    
      
    @Test
    public void getByPathVariableIdShouldLoadAndReturnObject() throws Exception {
    	mockMvc.perform(get("null/metric/"+firstMetric.getMetricId().toString()))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.metricId", is(firstMetric.getMetricId())))
        ;
    }
  
    @Test
    public void getByPathVariableIdShouldReturn404ForBogusId() throws Exception {
    	mockMvc.perform(get("null/metric/-123")).andExpect(status().isNotFound()).andExpect(jsonPath("$.message", is("null/metric/-123 could not be found.")));
    }
    
    @Test
    public void restMappingNotFoundShouldReturn404() throws Exception {
    	mockMvc.perform(get("null/metric/asdfasdf/asdfasdf"))
    	.andExpect(status().isNotFound())
    	 .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
        .andExpect(jsonPath("$.message", is("null/metric/asdfasdf/asdfasdf could not be found.")))
    	;
    }
    
    @Test
    public void createShouldPersistAndReturnObject() throws Exception {
	   long count = weightDaoService.getMetricService().count();	       
	   Metric metric = new Metric(); 
       
       mockMvc.perform(post("null/metric/").content(this.mapper.writeValueAsString(metric))
	   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
	   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.metricId").value(IsNull.notNullValue()))  
       ;
       
       assertEquals("count should increase by 1", count +1 , weightDaoService.getMetricService().count());
	}
     
    @Test
    public void updateShouldPersistExistingAndReturnObject() throws Exception {
       long count = weightDaoService.getMetricService().count();

       mockMvc.perform(post("null/metric/"+ firstMetric.getMetricId().toString())
    		   .content(this.mapper.writeValueAsString(firstMetric))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isOk())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.metricId", is(firstMetric.getMetricId())))
       ;
         
       assertEquals("count NOT should increase", count , weightDaoService.getMetricService().count());
  	}  
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForMismatchBetweenPathIdAndObjectId() throws Exception {	       
       String correctId =  firstMetric.getMetricId().toString();
       // this ID manipulation should be overwritten with path variable id
       firstMetric.setMetricId(-123);
       
       mockMvc.perform(post("null/metric/"+correctId)
    		   .content(this.mapper.writeValueAsString(firstMetric))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("null/metric/" +correctId +" could not be found.")))
       ;
  	} 
    
    @Test
    public void updateByPathVariableIdShouldReturn404ForBogusPathId() throws Exception {
    	mockMvc.perform(post("null/metric/-123")
    			.content(this.mapper.writeValueAsString(firstMetric))
    		   .accept(MediaType.APPLICATION_JSON).contentType(MediaType.APPLICATION_JSON)
    		   .with(csrf()))
    	.andExpect(status().isNotFound())
    	.andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
	    .andExpect(jsonPath("$.message", is("null/metric/-123 could not be found.")));
    }
    
    @Test
    public void deleteShouldDeleteAndReturnStatusOk() throws Exception {
        long count = weightDaoService.getMetricService().count();

        mockMvc.perform(delete("null/metric/"+ firstMetric.getMetricId().toString()).with(csrf()))
       .andExpect(status().isOk());  
       
       assertEquals("count should decrease by 1", count - 1 , weightDaoService.getMetricService().count());
    }
    
    @Test
    public void deleteShouldFailWithBogusId() throws Exception {
        long count = weightDaoService.getMetricService().count();

        mockMvc.perform(delete("null/metric/-123").with(csrf()))
       .andExpect(status().isNotFound())
       .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
       .andExpect(jsonPath("$.message", is("null/metric/-123 could not be found.")));  
       
       assertEquals("count should NOT decrease by 1", count , weightDaoService.getMetricService().count());
    }

    @Test
    public void listShouldReturnAllByDefault() throws Exception {
    	mockMvc.perform(get("null/metric/"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].metricId", is(firstMetric.getMetricId())))
        ;
    }
    
    @Test
    public void listShouldReturnAllByDefaultWithoutTrailUrlSlash() throws Exception {
    	mockMvc.perform(get("null/metric"))
         .andExpect(status().isOk())
         .andExpect(content().contentType(MediaType.APPLICATION_JSON_VALUE))
         .andExpect(jsonPath("$.", hasSize(is(20))))
        .andExpect(jsonPath("$.[0].metricId", is(firstMetric.getMetricId())))
        ;
    }
}