package com.schappet.weight.resource;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import com.schappet.weight.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/08/2016 09:07:58 CDT
 */
@RestController( value = "com_schappet_weight_resource_stepcount_resource" )
@RequestMapping( "/rest/stepcount" )
public class StepCountResource extends AbstractWeightApiResource {

    private static final Log log = LogFactory.getLog( StepCountResource.class );
    
    @RequestMapping( value = { "{stepCountId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public StepCount get( @PathVariable( "stepCountId" ) Integer stepCountId ) {
    	 StepCount stepCount = weightDaoService.getStepCountService().findById( stepCountId );
		 if (stepCount == null){
			 throw new EntityNotFoundException();
		 } 
	     return stepCount;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public StepCount create( @RequestBody @Valid StepCount stepCount ) {
		 weightDaoService.getStepCountService().save( stepCount );
		 return stepCount;
    }
    
    @RequestMapping( value = { "{stepCountId}" }, method = { RequestMethod.POST, RequestMethod.PUT }, produces = MediaType.APPLICATION_JSON_VALUE  )
    public StepCount update( @PathVariable( "stepCountId" ) Integer stepCountId, @RequestBody @Valid StepCount stepCount ) {
    	StepCount stepCountRecord = weightDaoService.getStepCountService().findById( stepCountId );
    	if ( stepCountRecord == null || !stepCountRecord.getId().equals(stepCount.getId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 weightDaoService.getStepCountService().getSession().flush();
         weightDaoService.getStepCountService().getSession().clear();
		 weightDaoService.getStepCountService().update( stepCount );
		 return stepCount;
    }
    
    @RequestMapping( value = { "{stepCountId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete( @PathVariable( "stepCountId" ) Integer stepCountId ) {
    	StepCount stepCount = weightDaoService.getStepCountService().findById( stepCountId );
		 if ( stepCount == null ){
			 throw new EntityNotFoundException();
		 } 
		 weightDaoService.getStepCountService().delete(stepCount);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<StepCount> list() {
    	 return weightDaoService.getStepCountService().list();
    }

}