package com.schappet.weight.resource;



import java.util.HashMap;
import java.util.Map;

import javax.servlet.http.HttpServletRequest;

import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:33:31 CST
 */
@RestController
@RequestMapping( "${pathPrefix}" )
public class DefaultResource extends AbstractWeightApiResource {

	@RequestMapping( value = "/**" , produces = MediaType.APPLICATION_JSON_VALUE )
	public ResponseEntity<Map<String, Object>> mappingNotFound( HttpServletRequest request ) {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put( "message", request.getRequestURI() + " could not be found." );
		return new ResponseEntity<Map<String, Object>>( map, HttpStatus.NOT_FOUND );
	}
	
}
