package com.schappet.weight.resource;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import com.schappet.weight.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/03/2016 06:46:13 CDT
 */
@RestController( value = "com_schappet_weight_resource_heartrate_resource" )
@RequestMapping( "/rest/heartrate" )
public class HeartRateResource extends AbstractWeightApiResource {


    private static final int DEFAULT_PERSON = 1;

    private static final Log log = LogFactory.getLog( HeartRateResource.class );
    
    @RequestMapping( value = { "{heartRateId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public HeartRate get( @PathVariable( "heartRateId" ) Integer heartRateId ) {
    	 HeartRate heartRate = weightDaoService.getHeartRateService().findById( heartRateId );
		 if (heartRate == null){
			 throw new EntityNotFoundException();
		 } 
	     return heartRate;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public HeartRate create( @RequestBody @Valid HeartRate heartRate ) {
    	
     	if (heartRate.getPerson() == null) {
     		heartRate.setPerson(weightDaoService.getPersonService().findById(DEFAULT_PERSON));
    	}
    	log.error("PersonName: " +heartRate.getPerson());
    	
		 weightDaoService.getHeartRateService().save( heartRate );
		 return heartRate;
    }
    
    @RequestMapping( value = { "{heartRateId}" }, method = { RequestMethod.POST, RequestMethod.PUT }, produces = MediaType.APPLICATION_JSON_VALUE  )
    public HeartRate update( @PathVariable( "heartRateId" ) Integer heartRateId, @RequestBody @Valid HeartRate heartRate ) {
    	HeartRate heartRateRecord = weightDaoService.getHeartRateService().findById( heartRateId );
    	if ( heartRateRecord == null || !heartRateRecord.getHeartRateId().equals(heartRate.getHeartRateId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 weightDaoService.getHeartRateService().getSession().flush();
         weightDaoService.getHeartRateService().getSession().clear();
		 weightDaoService.getHeartRateService().update( heartRate );
		 return heartRate;
    }
    
    @RequestMapping( value = { "{heartRateId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete( @PathVariable( "heartRateId" ) Integer heartRateId ) {
    	HeartRate heartRate = weightDaoService.getHeartRateService().findById( heartRateId );
		 if ( heartRate == null ){
			 throw new EntityNotFoundException();
		 } 
		 weightDaoService.getHeartRateService().delete(heartRate);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<HeartRate> list(@RequestParam(value="last", required = false, defaultValue="100") Integer limit) {
    	Person defaultPerson = weightDaoService.getPersonService().findById(DEFAULT_PERSON);

    	return weightDaoService.getHeartRateService().latest(defaultPerson, limit);

    }

}