package com.schappet.weight.resource;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.http.*;

import com.schappet.weight.domain.*;
import edu.uiowa.icts.exception.EntityNotFoundException;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:33:31 CST
 */
@RestController( value = "com_schappet_weight_resource_metric_resource" )
@RequestMapping( "/rest/metric" )
public class MetricResource extends AbstractWeightApiResource {

    private static final Log log = LogFactory.getLog( MetricResource.class );
    
    @RequestMapping( value = { "{metricId}" }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public Metric get( @PathVariable( "metricId" ) Integer metricId ) {
    	 Metric metric = weightDaoService.getMetricService().findById( metricId );
		 if (metric == null){
			 throw new EntityNotFoundException();
		 } 
	     return metric;
    }
    
    @RequestMapping( method = RequestMethod.POST, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Metric create( @RequestBody @Valid Metric metric ) {
		 weightDaoService.getMetricService().save( metric );
		 return metric;
    }
    
    @RequestMapping( value = { "{metricId}" }, method = { RequestMethod.POST, RequestMethod.PUT }, produces = MediaType.APPLICATION_JSON_VALUE  )
    public Metric update( @PathVariable( "metricId" ) Integer metricId, @RequestBody @Valid Metric metric ) {
    	Metric metricRecord = weightDaoService.getMetricService().findById( metricId );
    	if ( metricRecord == null || !metricRecord.getMetricId().equals(metric.getMetricId())){
			 throw new EntityNotFoundException(); 
		 } 
    	 weightDaoService.getMetricService().getSession().flush();
         weightDaoService.getMetricService().getSession().clear();
		 weightDaoService.getMetricService().update( metric );
		 return metric;
    }
    
    @RequestMapping( value = { "{metricId}" }, method = RequestMethod.DELETE, produces = MediaType.APPLICATION_JSON_VALUE )
    public String delete( @PathVariable( "metricId" ) Integer metricId ) {
    	Metric metric = weightDaoService.getMetricService().findById( metricId );
		 if ( metric == null ){
			 throw new EntityNotFoundException();
		 } 
		 weightDaoService.getMetricService().delete(metric);
	     return "";
    }
    
    @RequestMapping( value = {  "", "/"  }, method = RequestMethod.GET, produces = MediaType.APPLICATION_JSON_VALUE )
    public List<Metric> list() {
    	 return weightDaoService.getMetricService().listOrdered("dateAdded", "desc");
    }

}