package com.schappet.weight.controller;

import edu.uiowa.icts.spring.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;
import com.schappet.weight.dao.*;

/**
 * Generated by Protogen
 * Tue Apr 07 09:42:54 CDT 2015
 */
public abstract class AbstractWeightController {

    /*********** weightDaoService ****************/
    protected WeightDaoService weightDaoService;

    @Autowired 
    public void setWeightDaoService( WeightDaoService weightDaoService ) {
        this.weightDaoService = weightDaoService;
    }

    public String getUsername() {
        return SecurityContextHolder.getContext().getAuthentication().getName();
    }
}