package com.schappet.weight.controller;

import java.text.SimpleDateFormat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;

import com.schappet.weight.dao.WeightDaoService;

import edu.uiowa.icts.datatable.DataTable;

/**
 * Generated by Protogen
 * Tue Apr 07 09:42:54 CDT 2015
 */
public abstract class AbstractWeightController {

    protected final SimpleDateFormat shortDate = new SimpleDateFormat("yyyy-MM-dd");

    /*********** weightDaoService ****************/
    protected WeightDaoService weightDaoService;

    @Autowired 
    public void setWeightDaoService( WeightDaoService weightDaoService ) {
        this.weightDaoService = weightDaoService;
    }

    public String getUsername() {
        return SecurityContextHolder.getContext().getAuthentication().getName();
    }
    
    
    
	/**
	 * @param e
	 * @param draw
	 * @return {@link DataTable}
	 */
	protected DataTable datatableError( Exception e, String draw ) {
		String stackTrace = e.getMessage() + String.valueOf( '\n' );
		for ( StackTraceElement ste : e.getStackTrace() ) {
			stackTrace += ste.toString() + String.valueOf( '\n' );
		}
		DataTable error = new DataTable();
		error.setDraw( draw );
		error.setRecordsFiltered( 0 );
		error.setRecordsTotal( 0 );
		error.setError( stackTrace );
		return error;
	}
	
	
}