package com.schappet.weight.controller;

import java.text.SimpleDateFormat;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.core.context.SecurityContextHolder;

import com.schappet.weight.dao.WeightDaoService;

/**
 * Generated by Protogen
 * Tue Apr 07 09:42:54 CDT 2015
 */
public abstract class AbstractWeightController {

    protected final SimpleDateFormat shortDate = new SimpleDateFormat("yyyy-MM-dd");

    /*********** weightDaoService ****************/
    protected WeightDaoService weightDaoService;

    @Autowired 
    public void setWeightDaoService( WeightDaoService weightDaoService ) {
        this.weightDaoService = weightDaoService;
    }

    public String getUsername() {
        return SecurityContextHolder.getContext().getAuthentication().getName();
    }
}