package com.schappet.weight.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import com.schappet.weight.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/04/2016 15:26:20 CDT
 */
@Controller( value = "com_schappet_weight_controller_emailaddress_controller" )
@RequestMapping( "/emailaddress" )
public class EmailAddressController extends AbstractWeightController {

    private static final Log log = LogFactory.getLog( EmailAddressController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "emailAddressList", weightDaoService.getEmailAddressService().list() );
        return "/weight/emailaddress/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/weight/emailaddress/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = weightDaoService.getEmailAddressService().count( options );
            List<EmailAddress> emailAddressList = weightDaoService.getEmailAddressService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( EmailAddress emailAddress : emailAddressList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "emailId" :
							tableRow.put( dataName, emailAddress.getEmailId() );
							break;
						case "address" :
							tableRow.put( dataName, emailAddress.getAddress() );
							break;
						case "password" :
							tableRow.put( dataName, emailAddress.getPassword() );
							break;
						case "persons" :
							tableRow.put( dataName, ""); //emailAddress.getPersons().size() );
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/emailaddress/show?"+"emailId="+emailAddress.getEmailId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/emailaddress/edit?"+"emailId="+emailAddress.getEmailId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/emailaddress/delete?"+"emailId="+emailAddress.getEmailId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for EmailAddress", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "emailAddress", new EmailAddress() );

        return "/weight/emailaddress/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "emailId" ) Integer emailAddressId ) {


        model.addAttribute( "emailAddress", weightDaoService.getEmailAddressService().findById( emailAddressId ) );
        return "/weight/emailaddress/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "emailId" ) Integer emailAddressId ) {

        model.addAttribute( "emailAddress", weightDaoService.getEmailAddressService().findById( emailAddressId ) );
        return "/weight/emailaddress/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "emailAddress" ) EmailAddress emailAddress, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
			
			return "/weight/emailaddress/edit"; 
		} else {
			try {
				weightDaoService.getEmailAddressService().saveOrUpdate( emailAddress );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				weightDaoService.getEmailAddressService().merge( emailAddress );
			}
		}
		return "redirect:/emailaddress/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "emailId" ) Integer emailAddressId ) {

        model.addAttribute( "emailAddress", weightDaoService.getEmailAddressService().findById( emailAddressId ) );
        return "/weight/emailaddress/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "emailId" ) Integer emailAddressId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            weightDaoService.getEmailAddressService().delete( weightDaoService.getEmailAddressService().findById( emailAddressId ) );
        }
        return "redirect:/emailaddress/list";
    }
}