package com.schappet.weight.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import com.schappet.weight.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 04/02/2016 08:28:48 CDT
 */
@Controller( value = "com_schappet_weight_controller_person_controller" )
@RequestMapping( "/person" )
public class PersonController extends AbstractWeightController {

    private static final Log log = LogFactory.getLog( PersonController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "personList", weightDaoService.getPersonService().list() );
        return "/weight/person/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list(Model model) {
    	// needed for AngularJS grid/CRUD functionality
    			model.addAttribute( "emailAddressList", weightDaoService.getEmailAddressService().list() );
 
        return "/weight/person/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = weightDaoService.getPersonService().count( options );
            List<Person> personList = weightDaoService.getPersonService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( Person person : personList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "personId" :
							tableRow.put( dataName, person.getPersonId() );
							break;
						case "password" :
							tableRow.put( dataName, person.getPassword() );
							break;
						case "firstName" :
							tableRow.put( dataName, person.getFirstName() );
							break;
						case "lastName" :
							tableRow.put( dataName, person.getLastName() );
							break;
						case "middleName" :
							tableRow.put( dataName, person.getMiddleName() );
							break;
						case "activitys" :
							tableRow.put( dataName, person.getActivitys().size() );
							break;
						case "vitalss" :
							tableRow.put( dataName, person.getVitalss().size() );
							break;
						case "weights" :
							tableRow.put( dataName, person.getWeights().size() );
							break;
						case "emailAddress" :
							if( person.getEmailAddress() != null ){
								tableRow.put( dataName, person.getEmailAddress().toString() );
							}
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/person/show?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/person/edit?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/person/delete?"+"personId="+person.getPersonId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for Person", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "person", new Person() );
		model.addAttribute( "emailAddressList", weightDaoService.getEmailAddressService().list() );

        return "/weight/person/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {
		model.addAttribute( "emailAddressList", weightDaoService.getEmailAddressService().list() );


        model.addAttribute( "person", weightDaoService.getPersonService().findById( personId ) );
        return "/weight/person/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {

        model.addAttribute( "person", weightDaoService.getPersonService().findById( personId ) );
        return "/weight/person/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "person" ) Person person, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "emailAddressList", weightDaoService.getEmailAddressService().list() );

			return "/weight/person/edit"; 
		} else {
			try {
				weightDaoService.getPersonService().saveOrUpdate( person );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				weightDaoService.getPersonService().merge( person );
			}
		}
		return "redirect:/person/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "personId" ) Integer personId ) {

        model.addAttribute( "person", weightDaoService.getPersonService().findById( personId ) );
        return "/weight/person/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "personId" ) Integer personId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            weightDaoService.getPersonService().delete( weightDaoService.getPersonService().findById( personId ) );
        }
        return "redirect:/person/list";
    }
}