package com.schappet.weight.controller;



import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.validation.Valid;

import org.apache.commons.lang.StringUtils;
import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.NonUniqueObjectException;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.ui.ModelMap;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;

import edu.uiowa.icts.datatable.DataTable;
import edu.uiowa.icts.datatable.DataTableColumn;
import edu.uiowa.icts.datatable.DataTableRequest;
import com.schappet.weight.domain.*;
import edu.uiowa.icts.spring.GenericDaoListOptions;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/08/2016 09:07:58 CDT
 */
@Controller( value = "com_schappet_weight_controller_stepcount_controller" )
@RequestMapping( "/stepcount" )
public class StepCountController extends AbstractWeightController {

    private static final Log log = LogFactory.getLog( StepCountController.class );

    @RequestMapping( value = "list_alt", method = RequestMethod.GET )
    public String listNoScript(Model model) {
        model.addAttribute( "stepCountList", weightDaoService.getStepCountService().list() );
        return "/weight/stepcount/list_alt";
    }

    @RequestMapping( value = { "list", "", "/" }, method = RequestMethod.GET )
    public String list() {
        return "/weight/stepcount/list";
    }


	@ResponseBody
	@RequestMapping( value = "datatable" , produces = "application/json" )
	public DataTable datatable( @RequestBody DataTableRequest dataTableRequest, HttpServletRequest request,
		@RequestParam( value = "display" , required = false , defaultValue = "list" ) String display ) {
		
		String contextPath = request.getContextPath();
		GenericDaoListOptions options = dataTableRequest.getGenericDaoListOptions();

		try {

			Integer count = weightDaoService.getStepCountService().count( options );
            List<StepCount> stepCountList = weightDaoService.getStepCountService().list( options );
            
			List<LinkedHashMap<String, Object>> data = new ArrayList<LinkedHashMap<String, Object>>();

			for( StepCount stepCount : stepCountList ){

				LinkedHashMap<String, Object> tableRow = new LinkedHashMap<String, Object>();

				for ( DataTableColumn column : dataTableRequest.getColumns() ) {

					String headerName = column.getName();
					String dataName = column.getData();

					switch ( headerName ) {
						case "id" :
							tableRow.put( dataName, stepCount.getId() );
							break;
						case "value" :
							tableRow.put( dataName, stepCount.getValue() );
							break;
						case "measureStartDate" :
							tableRow.put( dataName, stepCount.getMeasureStartDate() );
							break;
						case "measureEndDate" :
							tableRow.put( dataName, stepCount.getMeasureEndDate() );
							break;
						case "person" :
							if( stepCount.getPerson() != null ){
								tableRow.put( dataName, stepCount.getPerson().toString() );
							}
							break;
						case "urls" :
							String urls = "";
							if( StringUtils.equals( "list", display ) ){
								urls += "<a href=\"" + contextPath + "/stepcount/show?"+"id="+stepCount.getId()+"\"><span class=\"glyphicon glyphicon-eye-open\"></a>";
								urls += "<a href=\"" + contextPath + "/stepcount/edit?"+"id="+stepCount.getId()+"\"><span class=\"glyphicon glyphicon-pencil\"></a>";
								urls += "<a href=\"" + contextPath + "/stepcount/delete?"+"id="+stepCount.getId()+"\"><span class=\"glyphicon glyphicon-trash\"></a>";
							} else {

							}
							tableRow.put( dataName, urls );
							break;
						default :
							tableRow.put( dataName, "[error: column " + headerName + " not supported]" );
							break;
					}
				}
				data.add( tableRow );
			}

			DataTable dataTable = new DataTable();
			dataTable.setDraw( dataTableRequest.getDraw() );
			dataTable.setRecordsFiltered( count );
			dataTable.setRecordsTotal( count );
			dataTable.setData( data );
			return dataTable;
			
		} catch ( Exception e ) {
			log.error( "error builing datatable json object for StepCount", e );
			return datatableError( e, dataTableRequest.getDraw() );
		}
		
	}

    @RequestMapping( value = "add", method = RequestMethod.GET )
    public String add( Model model ) {
        model.addAttribute( "stepCount", new StepCount() );
		model.addAttribute( "personList", weightDaoService.getPersonService().list() );

        return "/weight/stepcount/edit";
    }

    @RequestMapping( value = "edit", method = RequestMethod.GET )
    public String edit( ModelMap model, @RequestParam( value = "id" ) Integer stepCountId ) {
		model.addAttribute( "personList", weightDaoService.getPersonService().list() );


        model.addAttribute( "stepCount", weightDaoService.getStepCountService().findById( stepCountId ) );
        return "/weight/stepcount/edit";
    }

    @RequestMapping( value = "show", method = RequestMethod.GET )
    public String show( ModelMap model, @RequestParam( value = "id" ) Integer stepCountId ) {

        model.addAttribute( "stepCount", weightDaoService.getStepCountService().findById( stepCountId ) );
        return "/weight/stepcount/show";
    }

    @RequestMapping( value = "save", method = RequestMethod.POST )
    public String save(@Valid @ModelAttribute( "stepCount" ) StepCount stepCount, BindingResult result, Model model ) {


		if (result.hasErrors()) { 
					model.addAttribute( "personList", weightDaoService.getPersonService().list() );

			return "/weight/stepcount/edit"; 
		} else {
			try {
				weightDaoService.getStepCountService().saveOrUpdate( stepCount );
			} catch (NonUniqueObjectException e) {
				log.debug("Merging Results");
				weightDaoService.getStepCountService().merge( stepCount );
			}
		}
		return "redirect:/stepcount/list";
    }

    @RequestMapping( value = "delete", method = RequestMethod.GET )
    public String confirmDelete( ModelMap model, @RequestParam( value = "id" ) Integer stepCountId ) {

        model.addAttribute( "stepCount", weightDaoService.getStepCountService().findById( stepCountId ) );
        return "/weight/stepcount/delete";
    }

    @RequestMapping( value = "delete", method = RequestMethod.POST )
    public String doDelete( ModelMap model, @RequestParam( value = "submit" ) String submitButtonValue, @RequestParam( value = "id" ) Integer stepCountId ) {

        if ( StringUtils.equalsIgnoreCase( submitButtonValue, "yes" ) ) {
            weightDaoService.getStepCountService().delete( weightDaoService.getStepCountService().findById( stepCountId ) );
        }
        return "redirect:/stepcount/list";
    }
}