package com.schappet.weight.dao;

import java.util.List;

import com.schappet.spring.GenericDaoInterface;
import com.schappet.weight.domain.Activity;

/**
 * Generated by Protogen 
 * @since 04/11/2015 07:34:51 CDT
 */
public interface ActivityService extends GenericDaoInterface<Activity> {

	public Activity findById( Integer id );

	public List<Activity> latest(int defaultPerson, int i);

}