package com.schappet.weight.dao;

import java.util.List;

import com.schappet.weight.domain.Activity;
import com.schappet.weight.domain.Person;

import edu.uiowa.icts.spring.GenericDaoInterface;

/**
 * Generated by Protogen 
 * @since 04/11/2015 07:34:51 CDT
 */
public interface ActivityService extends GenericDaoInterface<Activity> {

	public Activity findById( Integer id );

	public List<Activity> latest(int defaultPerson, int i);

	List<Activity> lastNMonths(Person person, int count);

}