package com.schappet.weight.dao;

import com.schappet.spring.GenericDaoInterface;
import com.schappet.weight.domain.EmailAddress;



/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
public interface EmailAddressService extends GenericDaoInterface<EmailAddress> {

	public EmailAddress findById( Integer id );

}