package com.schappet.weight.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.weight.domain.*;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/03/2016 06:46:12 CDT
 */
@Transactional
@Repository( "com_schappet_weight_dao_HeartRateHome" )
public class HeartRateHome extends GenericDao<HeartRate> implements HeartRateService {

	public HeartRateHome() {
		setDomainName( "com.schappet.weight.domain.HeartRate" );
	}

	public HeartRate findById( Integer id ) {
		return (HeartRate) this.sessionFactory.getCurrentSession().get( HeartRate.class, id );
	}
	
	
	
	@Override
	public List<HeartRate> latest(Person person, int count) {
	
	     Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(HeartRate.class);
	     criteria.add(Restrictions.eq("person", person));
	     criteria.addOrder(Order.desc("measureDate"));
	     criteria.setMaxResults(count < 50 ? count : 50);
	     return criteria.list();
	     
		
	}

}