package com.schappet.weight.dao;

import edu.uiowa.icts.spring.*;

import java.util.List;

import com.schappet.weight.domain.*;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/03/2016 06:46:12 CDT
 */
public interface HeartRateService extends GenericDaoInterface<HeartRate> {

	public HeartRate findById( Integer id );
	public List<HeartRate> latest(Person defaultPerson, int i);

}