package com.schappet.weight.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.weight.domain.*;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:33:31 CST
 */
public interface MetricService extends GenericDaoInterface<Metric> {

	public Metric findById( Integer id );

}