package com.schappet.weight.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.weight.domain.*;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 02/14/2016 12:33:31 CST
 */
@Transactional
@Repository( "com_schappet_weight_dao_MetricHome" )
public class MetricHome extends GenericDao<Metric> implements MetricService {

	public MetricHome() {
		setDomainName( "com.schappet.weight.domain.Metric" );
	}

	public Metric findById( Integer id ) {
		return (Metric) this.sessionFactory.getCurrentSession().get( Metric.class, id );
	}

}