package com.schappet.weight.dao;

import com.schappet.spring.*;
import com.schappet.weight.domain.*;

import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
@Repository("com_schappet_weight_dao_PersonHome")
@Transactional
public class PersonHome extends GenericDao<Person> implements PersonService {

	private static final Log log = LogFactory.getLog( PersonHome.class );

	public PersonHome() {
		setDomainName( "com.schappet.weight.domain.Person" );
	}

	public Person findById( Integer id ) {
		return (Person) this.sessionFactory.getCurrentSession().get( Person.class, id );
	}

}