package com.schappet.weight.dao;

import com.schappet.spring.GenericDaoInterface;
import com.schappet.weight.domain.Person;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
public interface PersonService extends GenericDaoInterface<Person> {

	public Person findById( Integer id );

}