package com.schappet.weight.dao;

import java.util.List;

import org.hibernate.Criteria;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.schappet.weight.domain.Person;
import com.schappet.weight.domain.StepCount;

import edu.uiowa.icts.spring.GenericDao;

/**
 * Generated by Protogen 
 * @see <a href="https://github.com/ui-icts/protogen">https://github.com/ui-icts/protogen</a>
 * @since 06/08/2016 09:07:58 CDT
 */
@Transactional
@Repository( "com_schappet_weight_dao_StepCountHome" )
public class StepCountHome extends GenericDao<StepCount> implements StepCountService {

	public StepCountHome() {
		setDomainName( "com.schappet.weight.domain.StepCount" );
	}

	public StepCount findById( Integer id ) {
		return (StepCount) this.sessionFactory.getCurrentSession().get( StepCount.class, id );
	}

	
	
	@Override
	public List<StepCount> latest(Person person, int count) {
	
	     Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(StepCount.class);
	     criteria.add(Restrictions.eq("person", person));
	     criteria.addOrder(Order.desc("measureEndDate"));
	     criteria.setMaxResults(count < 50 ? count : 50);
	     return criteria.list();
	     
		
	}
}