package com.schappet.weight.dao;

import java.util.Date;
import java.util.List;

import com.schappet.spring.GenericDaoInterface;
import com.schappet.weight.domain.Vitals;

/**
 * Generated by Protogen 
 * @since 04/11/2015 07:34:51 CDT
 */
public interface VitalsService extends GenericDaoInterface<Vitals> {

	public Vitals findById( Integer id );
	public Vitals findByPersonIdAndDate( Integer id, Date date );
	public List<Vitals> latest(int defaultPerson, int i);

}