package com.schappet.weight.dao;

import com.schappet.spring.GenericDaoInterface;
import com.schappet.weight.domain.Vitals;

/**
 * Generated by Protogen 
 * @since 04/11/2015 07:34:51 CDT
 */
public interface VitalsService extends GenericDaoInterface<Vitals> {

	public Vitals findById( Integer id );

}