package com.schappet.weight.dao;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.schappet.spring.GenericDao;
import com.schappet.weight.domain.Vitals;

/**
 * Generated by Protogen 
 * @since 04/11/2015 07:34:51 CDT
 */
@Repository("com_schappet_weight_dao_VitalsHome")
@Transactional
public class VitalsHome extends GenericDao<Vitals> implements VitalsService {

	private static final Log log = LogFactory.getLog( VitalsHome.class );

	public VitalsHome() {
		setDomainName( "com.schappet.weight.domain.Vitals" );
	}

	public Vitals findById( Integer id ) {
		return (Vitals) this.sessionFactory.getCurrentSession().get( Vitals.class, id );
	}

}