package com.schappet.weight.dao;

import edu.uiowa.icts.spring.*;
import com.schappet.weight.domain.*;
import org.apache.commons.logging.LogFactory;
import org.apache.commons.logging.Log;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
@Repository("com_schappet_weight_dao_WeightHome")
@Transactional
public class WeightHome extends GenericDao<Weight> implements WeightService {

	private static final Log log = LogFactory.getLog( WeightHome.class );

	public WeightHome() {
		setDomainName( "com.schappet.weight.domain.Weight" );
	}

	public Weight findById( Integer id ) {
		return (Weight) this.sessionFactory.getCurrentSession().get( Weight.class, id );
	}

}