package com.schappet.weight.dao;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.hibernate.Criteria;
import org.hibernate.criterion.Conjunction;
import org.hibernate.criterion.Disjunction;
import org.hibernate.criterion.Order;
import org.hibernate.criterion.Restrictions;
import org.springframework.stereotype.Repository;
import org.springframework.transaction.annotation.Transactional;

import com.schappet.weight.domain.Person;
import com.schappet.weight.domain.Weight;

import edu.uiowa.icts.spring.GenericDao;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
@Repository("com_schappet_weight_dao_WeightHome")
@Transactional
public class WeightHome extends GenericDao<Weight> implements WeightService {
    protected final SimpleDateFormat shortDate = new SimpleDateFormat("yyyy-MM-dd");

    
	private static final Log log = LogFactory.getLog( WeightHome.class );

	public WeightHome() {
		setDomainName( "com.schappet.weight.domain.Weight" );
	}

	public Weight findById( Integer id ) {
		return (Weight) this.sessionFactory.getCurrentSession().get( Weight.class, id );
	}

	public Weight latest(Person person) {
		
	     Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Weight.class);
	     criteria.add(Restrictions.eq("person", person));
	     criteria.addOrder(Order.desc("weightInDate"));
	     criteria.setMaxResults(1);
	     return (Weight) criteria.uniqueResult();
		 
	}

	@Override
	public List<Weight> latest(Person person, int count) {
	    Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Weight.class);
	    criteria.add(Restrictions.eq("person", person));
	    criteria.addOrder(Order.desc("weightInDate"));
	    criteria.setMaxResults(count < 50 ? count : 50);
	    @SuppressWarnings("unchecked")
		List<Weight> list = criteria.list();
	    java.util.Collections.reverse(list);
	    return  list;
		 
	}


	@Override
	public List<Weight> lastNMonths(Person person, int count) {
		
		int EXTRA_DAYS = 5;
		
		Disjunction or = Restrictions.disjunction();
		
	    Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Weight.class);
	    criteria.add(Restrictions.eq("person", person));
	    
		Calendar calendar1 = Calendar.getInstance(); // this would default to now
		calendar1.add(Calendar.DAY_OF_MONTH, -( EXTRA_DAYS )) ;

		Conjunction and1 = Restrictions.conjunction();	
		and1.add(Restrictions.ge("weightInDate", calendar1.getTime()));
		calendar1.add(Calendar.DAY_OF_MONTH, EXTRA_DAYS);
		and1.add(Restrictions.le("weightInDate", calendar1.getTime()));
		or.add(and1);
	    
	    for (int i = 0 ; i <= count ; i++) {

	    	
			Calendar calendar = Calendar.getInstance(); // this would default to now
			calendar.add(Calendar.DAY_OF_MONTH, -( i * 30 )) ;
		
			Conjunction and = Restrictions.conjunction();	
			and.add(Restrictions.ge("weightInDate", calendar.getTime()));
			calendar.add(Calendar.DAY_OF_MONTH, 1);
			and.add(Restrictions.le("weightInDate", calendar.getTime()));
			
	    	or.add(and);
		}
		
	    criteria.add(or);
	     
	    criteria.setMaxResults(count < 12 ? count : 12);
	    return criteria.list();
		 
	}
	
	@Override
	public List<Weight> between(Person person, Date start, Date end) {
		  Criteria criteria = this.sessionFactory.getCurrentSession().createCriteria(Weight.class);
		  criteria.add(Restrictions.eq("person", person));
		  criteria.add(Restrictions.between("weightInDate", start, end));

		  criteria.addOrder(Order.desc("weightInDate"));
		// TODO Auto-generated method stub
		return criteria.list();
	}

}