package com.schappet.weight.dao;

import java.util.Date;
import java.util.List;

import com.schappet.weight.domain.Person;
import com.schappet.weight.domain.Weight;

import edu.uiowa.icts.spring.GenericDaoInterface;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
public interface WeightService extends GenericDaoInterface<Weight> {

	public Weight findById( Integer id );

	public Weight latest(Person person);
	public List<Weight> latest(Person person, int count);
	
	public List<Weight> between(Person person, Date start, Date end);

	List<Weight> lastNMonths(Person person, int count);

}