package com.schappet.weight.dao;

import java.util.Date;
import java.util.List;

import com.schappet.weight.domain.Weight;

import edu.uiowa.icts.spring.GenericDaoInterface;

/**
 * Generated by Protogen 
 * @since 04/07/2015 08:12:26 CDT
 */
public interface WeightService extends GenericDaoInterface<Weight> {

	public Weight findById( Integer id );

	public Weight latest(int personId);
	public List<Weight> latest(int personId, int count);
	
	public List<Weight> between(int personId, Date start, Date end);

}